export const config = Object.freeze({
  gameVersion: "0.4.2",
  testVersion: 1,
  particleRuleVersion: 5,
  battleCoreVersion: 1,
  astrologyRuleVersion: 4,
  timezone: "Asia/Tokyo",
  dailyResetHour: 4,
  particle: {
    durationMs: 30000,
    durationByVersion: { 1: 60000, 2: 60000, 3: 30000, 4: 30000, 5: 30000 },
    count: 100,
    width: 960,
    height: 540,
    cooldownMs: 500,
    hitRadiusByVersion: { 1: 26, 2: 36, 3: 72, 4: 72, 5: 72 },
    events: {
      deviation: 4,
      precursor: 4,
      emergence: 3,
      desync: 3,
      "hidden-rule": 2,
    },
  },
  economy: {
    initialRC: 300,
    dailyAccessRC: 100,
    dailyTestRC: { card: 20, particle: 30 },
    drawCost: 100,
    tenDrawCost: 900,
    duplicateShards: 10,
  },
  battle: {
    dailyLimit: 5,
    completionRC: 10,
    winEXP: 20,
    loseEXP: 5,
    maxTurns: 12,
  },
  senses: ["awareness", "foresight", "insight", "intuition", "resonance"],
  labels: {
    awareness: "察知",
    foresight: "予見",
    insight: "洞察",
    intuition: "感応",
    resonance: "共鳴",
  },
});
